### ISSUE TITLE
BIZ: Campaign details page. Add UOM.

### ISSUE THREAD

**Issue by winwisely02** [getcouragenow/main#118]
Where: Campaign details page

![Screen Shot 2020-01-03 at 11 54 23 am](https://user-images.githubusercontent.com/56081026/71739769-0707bc00-2e20-11ea-9e39-d3234341c5e1.png)

Length of action should have the unit of measurement next to the number (e.g., 5 days). 
That data is here https://docs.google.com/spreadsheets/d/1T8rAqeU2J_gEvryhRIqWVtmh6zxwE2sRXX2Iqf__GOg/edit#gid=0&range=I:I

**Comment by thevzurd** [comment]
done
