### ISSUE TITLE
Wire Up Existing Sys-Share Proxy and Sys to Maintemplatev2

### ISSUE THREAD

**Issue by gutterbacon** [getcouragenow/main#7]
## Background

`sys-share` and `sys` has been refactored "just-enough" to conform to the spec specified at [the `main` repo README](https://github.com/getcouragenow/main#imports) and [modular architecture document here](https://github.com/getcouragenow/shared/blob/master/doc/MODULES.md). 

Now we need to build it from the top (this repo)

## What needs to be done

- Current `sys/main/pkg` needs to call `sys-share/pkg/service-proxy` instead of directly calling generated *rpc* package, to satisfy the proxy design pattern from the spec.

- Wire up current code at `sys/main/pkg` and `sys/pkg` to the `main/deploy/templates/maintemplatev2`. Should conform to the v2 spec mentioned in the background documents (single binary).

- Make sure the top->bottom recursive build and tests succeeded, use current **Makefile** to drive the builds.

**Comment by WinWisely268** [comment]
### Steps To Do:

#### Sys-Share

1. Fully utilize `sys-share/pkg` as a proxy for sys-account (for now, 80% done).

For example:
![screenshot_2020-10-05-102706](https://user-images.githubusercontent.com/63658381/95068807-48056780-06f5-11eb-9561-98a3f2f33177.png)

-  [] `sys-share` will provide both in-process and out-of-process interface to the protobuf service ( like the spec)
-  [] Once the proxy is done, actually calls it from the `sys/main/pkg` where it will cater to both the needs from sdk-cli or from the actual `sys-*` server that is defined there.
- [] The `sys` in turn will be called from the maintemplate (v2 atm), So basically the maintemplatev2 will be a sort of simulation of how the actual mod (or the maintemplate) will be done.
- [] Make sure everything builds from the bottom-up.

**Comment by gutterbacon** [comment]
### Steps To Do:

- [X] Fully utilize `sys-share/pkg` as a proxy for sys-account (for now, 80% done).

For example:
![screenshot_2020-10-05-102706](https://user-images.githubusercontent.com/63658381/95068807-48056780-06f5-11eb-9561-98a3f2f33177.png)

-  [] `sys-share` will provide both in-process and out-of-process interface to the protobuf service ( like the spec)
-  [] Once the proxy is done, actually calls it from the `sys/main/pkg` where it will cater to both the needs from sdk-cli or from the actual `sys-*` server that is defined there.
- [] The `sys` in turn will be called from the maintemplate (v2 atm), So basically the maintemplatev2 will be a sort of simulation of how the actual mod (or the maintemplate) will be done.
- [] Make sure everything builds from the bottom-up.
